name: d4_interpolate
version: 1.0.4
description: Interpolate numbers, colors, strings, arrays, objects, whatever!
repository: https://github.com/luizbarboza/d4_interpolate

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  d4_color: ^1.0.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.5